create database company;
use company;
create table PROJECT(
PNO int primary key,
PLOC varchar(50),
PNAME varchar(50));
create table DEPT(
DEPTNO INT PRIMARY KEY,
DNAME VARCHAR(50),
DLOC VARCHAR(40));
CREATE TABLE EMPLOYEE(
EMPNO INT ,
ENAME VARCHAR(50),
MGR_NO INT,
HIREDATE DATE,
SAL INT,
DEPTNO INT,
PRIMARY KEY(EMPNO,DEPTNO),
FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO));
CREATE TABLE INCENTIVES(
EMPNO INT,
INCENTIVE_DATE DATE,
INCENCTIVE_AMOUNT INT,
PRIMARY KEY(EMPNO, INCENTIVE_DATE),
FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO));
CREATE TABLE ASSIGNED_TO(
EMPNO INT,
PNO INT,
JOB_ROLE VARCHAR(20),
PRIMARY KEY(EMPNO, PNO),
FOREIGN KEY(EMPNO) REFERENCES EMPLOYEE(EMPNO),
FOREIGN KEY (PNO) REFERENCES PROJECT(PNO));

INSERT INTO DEPT VALUES
(1,'IT','BENGALURU'),
(2,'FINANCE','HYDERABAD'),
(3,'HR','MYSURU'),
(4,'SALES','PUNE'),
(5,'MARKETING','DELHI'),
(6,'CSE','BENGALURU');